Make sure we exit if script fails

diff --git a/scripts/install_dev b/scripts/install_dev
--- a/scripts/install_dev
+++ b/scripts/install_dev
@@ -3,6 +3,10 @@
 # dependencies, then builds everything using `catkin_make_isolated` and
 # installs it in `/opt/ros/indigo/`.
 
+# Make sure we exit if a failure happens.
+# http://stackoverflow.com/questions/19622198/what-does-set-e-mean-in-a-bash-script
+set -e
+
 # Make sure we're running this from the correct directory
 if [ ! -d ~/catkin_ws/src/openag_brain/ ] ; then
   echo "Location \"~/catkin_ws/src/openag_brain\" does not exist. openag_brain must be placed in \"~/catkin_ws/src\" for this script to work." && exit 1
